# Where things are
source:      .
destination: ./_site
layouts_dir:     ./_layouts
data_dir: ./_data
exclude: ['node_modules']

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "" # does not include hostname

# Generating pages
page_gen-dirs: true
page_gen:

  - data: 'parent-activities'
    template: 'homepage'
    name: 'slug'
    dir: ''
