site_url: http://localhost:4000
redirect_url: localhost:4000
cdn: http://localhost:4000/cdn
ga: UA-80145536-1
typeform_enquiry: https://mcb2.typeform.com/to/fR5QxL
typeform_guide_signup: https://mcb2.typeform.com/to/TcoLi1

# site_url: https://staging.wilderness-now.com
# redirect_url: staging.wilderness-now.com
# cdn: https://cdn.wilderness-now.com
# ga: UA-80145536-1
# typeform_enquiry: https://mcb2.typeform.com/to/fR5QxL
# typeform_guide_signup: https://mcb2.typeform.com/to/TcoLi1

# site_url: https://www.wilderness-now.com
# redirect_url: www.wilderness-now.com
# cdn: https://cdn.wilderness-now.com
# ga: UA-80145536-2
# typeform_enquiry: https://mcb2.typeform.com/to/roZWv3
# typeform_guide_signup: https://mcb2.typeform.com/to/HZmPUP

