#cdn: //d3fybqvnrweshl.cloudfront.net
#site_url: http://aws-website-wildernessnow-yib3s.s3-website-us-east-1.amazonaws.com/
site_url: http://localhost:4000/
redirect_url: localhost:4000/
cdn: https://cdn.wilderness-now.com

