site_url: http://localhost:4000/
redirect_url: localhost:4000
cdn: /cdn

# site_url: https://staging.wilderness-now.com/
# redirect_url: staging.wilderness-now.com
# cdn: https://cdn.wilderness-now.com

# site_url: https://wilderness-now.com/
# redirect_url: wilderness-now.com
# cdn: https://cdn.wilderness-now.com

